In [1]:
arr=[[1,2,3],[4,5,6],[7,8,9]]

In [2]:
arr

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [3]:
x=np.array(arr)

NameError: name 'np' is not defined

In [6]:
import numpy as np

In [7]:
x=np.array(arr)

In [8]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
x.sum(axis=0)

array([12, 15, 18])

In [10]:
x.sum(axis=1)

array([ 6, 15, 24])

In [11]:
x.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [12]:
x.flat

In [13]:
for i in x.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [14]:
x.ndim

2

In [15]:
x.size

9

In [16]:
x.nbytes

36

In [17]:
one=np.array([1,45,78,555,123])

In [18]:
one

array([  1,  45,  78, 555, 123])

In [20]:
one.argmax()

3

one.argmin()

In [24]:
one.argmin()

0

In [25]:
one.argsort()

array([0, 1, 2, 4, 3], dtype=int64)