In [2]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5])

In [8]:
print(arr)

NameError: name 'arr' is not defined

In [ ]:
zeros=np.zeros((2,5))

In [7]:
zeros

NameError: name 'zeros' is not defined

In [5]:
a=np.array([1,2,3,4])

In [6]:
print(a)

[1 2 3 4]


In [9]:
zeros=np.zeros((2,5))

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
a=np.array([1,2,3,4])

In [19]:
a

array([1, 2, 3, 4])

In [20]:
x=np.arange(15)

In [21]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
x=np.linspace(0,10,16)

In [30]:
x

array([ 0.        ,  0.66666667,  1.33333333,  2.        ,  2.66666667,
        3.33333333,  4.        ,  4.66666667,  5.33333333,  6.        ,
        6.66666667,  7.33333333,  8.        ,  8.66666667,  9.33333333,
       10.        ])

In [32]:
x = np.empty((4,6))

In [33]:
x

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.02359984e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 1.24610383e-306,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.42417222e-306,
        1.33512648e-306, 7.56596412e-307, 1.42410974e-306]])

In [11]:
import numpy as np

In [17]:
x=np.array((3,3))